"""
Define common constants.
"""

EMB_INIT_RANGE = 1.0

PAD_TOKEN = '<PAD>'
PAD_ID = 0
UNK_TOKEN = '<UNK>'
UNK_ID = 1
SOS_TOKEN = '<SOS>'
SOS_ID = 2
EOS_TOKEN = '<EOS>'
EOS_ID = 3

VOCAB_PREFIX = [PAD_TOKEN, UNK_TOKEN, SOS_TOKEN, EOS_TOKEN]

INFINITY_NUMBER = 1e12
SMALL_NUMBER = 1e-12
